// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9h5UR34nUwE_EO5pnp5i9XlJwCHft70',
    appId: '1:983110106150:web:c7bee1f9c7733b149afae7',
    messagingSenderId: '983110106150',
    projectId: 'whatapp-778d3',
    authDomain: 'whatapp-778d3.firebaseapp.com',
    databaseURL: 'https://whatapp-778d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatapp-778d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-4rVKdaOyTEl5Vkf6GS6A0TI4jQjdiw',
    appId: '1:983110106150:android:9d7858339e73b4749afae7',
    messagingSenderId: '983110106150',
    projectId: 'whatapp-778d3',
    databaseURL: 'https://whatapp-778d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatapp-778d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsfgDAAt3TFSYuRuLOIy9p5f7b8Tcer5M',
    appId: '1:983110106150:ios:70713a7cf8f617219afae7',
    messagingSenderId: '983110106150',
    projectId: 'whatapp-778d3',
    databaseURL: 'https://whatapp-778d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatapp-778d3.appspot.com',
    iosClientId: '983110106150-n3ffjs8k80kgtdnperhr6bqib89rjjb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsfgDAAt3TFSYuRuLOIy9p5f7b8Tcer5M',
    appId: '1:983110106150:ios:b53d4cfb803d23699afae7',
    messagingSenderId: '983110106150',
    projectId: 'whatapp-778d3',
    databaseURL: 'https://whatapp-778d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatapp-778d3.appspot.com',
    iosClientId: '983110106150-63op8ueihr1updc63biepeqqrj8e82ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
